# Github action workflow to render R markdwon when PR is opened

on:
  pull_request:
    types: [opened, reopened]

name: render-jnotebook

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Docker container to compile assets
        uses: addnab/docker-run-action@v3
        with:
          image: quay.io/cdis/jupyter-notebook:latest
          options: -v ${{ github.workspace }}:/home
          run: |
            cd /home
            JUPYTER_FILES=$( find . -name "*ipynb" |  tr '\n' ' ')
            echo $RMD_FILES
            jupyter notebook execute $JUPYTER_FILES
      - name: Test file
        run: |
          ls src/*
      - uses: stefanzweifel/git-auto-commit-action@v4
