name: Run Jupyter Notebooks

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  run_notebooks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t notebook-runner .
#      working-directory: path/to/your/dockerfile/directory

    - name: Run Jupyter Notebooks
      run: |
        docker run --rm -v $GITHUB_WORKSPACE:/workspace notebook-runner bash -c 'find /workspace -name "*.ipynb" -exec jupyter nbconvert --to notebook --execute {} \;'

